Рзметка страницы индекса
htmlacademy-htmlcss/2320775-sedona-36 pull request #2
Opened 2023-01-24 20:18 UTC by AnnaVita1

2023-01-25 11:37 UTC, summertime-fms requested changes

2023-01-25 11:37 UTC, summertime-fms commented on catalog.html
> +          <li class="navigation-item">
Мне кажется тебе удобнее будет поставить лого вне списка. В списке обычно однотипные элементы. Ссылки навигации такими являются, а лого нет. Сделай лучше ссылку с логотипом перед началом списка.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +        <h3>
Лучше просто <p> т.к. после заголовка обычно идет какой то контент, текст, ссылки, а сразу заголовок после заголовка немного странно.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <figcaption><strong>Настоящий городок</strong></figcaption>
Стронг с новой строки давай

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <h3>Опытный персонал и качественное обслуживание!</h3>
Аналогично замечанию выше. Давай параграфом.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <h3>Укажите предполагаемые даты поездки, и мы покажем вам лучшие предложения гостиниц в Седоне</h3>
Аналогично выше

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +      <section class="newsletter">
Я бы не стал это упаковывать в футер, хотя кажется на первый ызгляд логичным т.к. блок на обеих страницах. Футер обычно это соц-сети, копирайт, лого. Иногда еще навигация. Этот блок тут тянет на самостоятельную часть страницы, он может быть в мейне. Однако, если тебе нравится так, ошибкой это не будет.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +        <img class="newsletter-background" src="#" alt="Фоновые очертания гор Аризоны">
Это фоновое изображение, оно служит исключительно для декоративных целей.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <h3>Только полезная информация и никакого спама,<br>
параграф

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +                <a class="button" href="https://vk.com/htmlacademy">
Погугли про атрибуты rel="nofollow noreferer" тут они уместны будут.

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <p class="copyright"><a href="https://htmlacademy.ru" class="htmlacademy-link">.html academy</a>
ссылка с новой строки

2023-01-25 11:37 UTC, summertime-fms commented on index.html
> +          <p class="copyright"><a href="https://htmlacademy.ru" class="htmlacademy-link">.html academy</a>
Да и параграф не нужен, лишняя обертка. Просто ссылку оставь

2023-01-25 12:13 UTC, AnnaVita1 commented on catalog.html
> +          <li class="navigation-item">
Да, логично вполне. Вынесла за список.

2023-01-25 12:20 UTC, AnnaVita1 commented on index.html
> +        <h3>
Не прогрузилась картинка, я подумала, может h3 поменять на p например?

2023-01-25 12:20 UTC, AnnaVita1 commented on index.html
> +          <figcaption><strong>Настоящий городок</strong></figcaption>
Сделала.

2023-01-25 12:22 UTC, AnnaVita1 commented on index.html
> +      <section class="newsletter">
Да, я тоже думала, секция это или футер, решила, что футер. Потому что в футере совсем тогда ничего не останется, там даже текста никакого))

2023-01-25 12:22 UTC, AnnaVita1 commented on index.html
> +        <img class="newsletter-background" src="#" alt="Фоновые очертания гор Аризоны">
Хорошо, удаляю.

2023-01-25 12:25 UTC, AnnaVita1 commented on index.html
> +          <p class="copyright"><a href="https://htmlacademy.ru" class="htmlacademy-link">.html academy</a>
Удалила, оставила ссылку. Думала что так проще в стилях будет двигать потом элемент))

2023-01-25 12:34 UTC, AnnaVita1 commented on index.html
> +          <h3>Опытный персонал и качественное обслуживание!</h3>
Поменяла на параграф 95 строку

2023-01-25 12:34 UTC, AnnaVita1 commented on index.html
> +          <h3>Укажите предполагаемые даты поездки, и мы покажем вам лучшие предложения гостиниц в Седоне</h3>
Поменяла на параграф 116 стр

2023-01-25 12:35 UTC, AnnaVita1 commented on index.html
> +          <h3>Только полезная информация и никакого спама,<br>
Поставила 127 стр параграф

2023-01-25 13:04 UTC, AnnaVita1 commented on index.html
> +                <a class="button" href="https://vk.com/htmlacademy">
Поставила ко всем трём ссылкам.

2023-01-26 14:19 UTC, summertime-fms requested changes

2023-01-26 14:19 UTC, summertime-fms commented on catalog.html
> +                    <input class="select-input" type="radio" name="hotel" value="shaving-supplies" checked>Гостиница</label>
У чеков разные имена, а у радиокнопок одинаковые имена но разный value, т.к. выбирается одно из общего.

2023-01-26 14:19 UTC, summertime-fms commented on catalog.html
> +        <form class="catalog-price" action="https://echo.htmlacademy.ru/" method="get">
Это все одна форма, мы в ней выставляем параметры к фильтрации.

2023-01-26 14:19 UTC, summertime-fms commented on catalog.html
> +        <form class="find-hotels-select" action="https://echo.htmlacademy.ru/" method="post">
В макете нет кнопки отправки этой формы. Тут допускается отсутствие тега form. Просто селект оставим давай.

2023-01-26 14:19 UTC, summertime-fms commented on catalog.html
> +        <a class="button button-light" href="#" >
Думаю эти кнопки сгруппировать можно в див, чтобы потом сетку построить.

2023-01-26 14:22 UTC, AnnaVita1 commented on catalog.html
> +        <a class="button button-light" href="#" >
Сделала

2023-01-26 14:31 UTC, AnnaVita1 commented on catalog.html
> +        <form class="find-hotels-select" action="https://echo.htmlacademy.ru/" method="post">
Точно. Недоглядела. Исправила.

2023-01-26 14:36 UTC, AnnaVita1 commented on catalog.html
> +        <form class="catalog-price" action="https://echo.htmlacademy.ru/" method="get">
Изменила.

2023-01-26 14:43 UTC, AnnaVita1 commented on catalog.html
> +                    <input class="select-input" type="radio" name="hotel" value="shaving-supplies" checked>Гостиница</label>
Да, верно. Испарвила

2023-01-26 16:18 UTC, merged